export const team_data = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    phoneNumber: "123-456-7890",
    authority: "Admin",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 25,
    phoneNumber: "234-567-8901",
    authority: "User",
  },
  {
    id: 3,
    name: "Michael Johnson",
    email: "michael.j@example.com",
    age: 28,
    phoneNumber: "345-678-9012",
    authority: "Manager",
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily.davis@example.com",
    age: 35,
    phoneNumber: "456-789-0123",
    authority: "Admin",
  },
  {
    id: 5,
    name: "Daniel Wilson",
    email: "daniel.wilson@example.com",
    age: 22,
    phoneNumber: "567-890-1234",
    authority: "User",
  },
  {
    id: 6,
    name: "Sophia Brown",
    email: "sophia.brown@example.com",
    age: 29,
    phoneNumber: "678-901-2345",
    authority: "Manager",
  },
  {
    id: 7,
    name: "James Anderson",
    email: "james.anderson@example.com",
    age: 40,
    phoneNumber: "789-012-3456",
    authority: "User",
  },
  {
    id: 8,
    name: "Ava Martinez",
    email: "ava.martinez@example.com",
    age: 32,
    phoneNumber: "890-123-4567",
    authority: "Admin",
  },
  {
    id: 9,
    name: "William Lee",
    email: "william.lee@example.com",
    age: 26,
    phoneNumber: "901-234-5678",
    authority: "User",
  },
];
